### ISSUE TITLE
sqlparse-0.4.1 does not work with schema_migrate of esgf-security

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-ansible#149]
**Describe the bug**
TASK [schema_migrate : Easy Install schema migration script esgf_security_initialize] failed with sqlparse-0.4.1.

**To Reproduce**
$ sudo sh -c "source /usr/local/conda/bin/activate schema-migrate && easy_install /tmp/esgf_security-0.1.7-py2.7.egg"
WARNING: The easy_install command is deprecated and will be removed in a future version.
Processing esgf_security-0.1.7-py2.7.egg
removing '/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/esgf_security-0.1.7-py2.7.egg' (and everything under it)
creating /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/esgf_security-0.1.7-py2.7.egg
Extracting esgf_security-0.1.7-py2.7.egg to /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages
esgf-security 0.1.7 is already the active version in easy-install.pth
Installing esgf_security_initialize script to /usr/local/conda/envs/schema-migrate/bin
Installed /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/esgf_security-0.1.7-py2.7.egg
Processing dependencies for esgf-security==0.1.7
Searching for sqlparse
Reading https://pypi.org/simple/sqlparse/
Downloading https://files.pythonhosted.org/packages/a2/54/da10f9a0235681179144a5ca02147428f955745e9393f859dec8d0d05b41/sqlparse-0.4.1.tar.gz#sha256=0f91fd2e829c44362cbcfab3e9ae12e22badaa8a29ad5ff599f9ec109f0454e8
Best match: sqlparse 0.4.1
Processing sqlparse-0.4.1.tar.gz
Writing /tmp/easy_install-6ZGABz/sqlparse-0.4.1/setup.cfg
Running sqlparse-0.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6ZGABz/sqlparse-0.4.1/egg-dist-tmp-KfKl7V
Traceback (most recent call last):
  File "/usr/local/conda/envs/schema-migrate/bin/easy_install", line 11, in <module>
    sys.exit(main())
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2321, in main
    **kw
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 713, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-6ZGABz/sqlparse-0.4.1/setup.py", line 12, in <module>
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/distutils/core.py", line 124, in setup
    dist.parse_config_files()
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/dist.py", line 702, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/config.py", line 121, in parse_configuration
    meta.parse()
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/setuptools/config.py", line 349, in _parse_attr
    module = import_module(module_name)
  File "/usr/local/conda/envs/schema-migrate/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/easy_install-6ZGABz/sqlparse-0.4.1/sqlparse/__init__.py", line 11, in <module>
  File "/tmp/easy_install-6ZGABz/sqlparse-0.4.1/sqlparse/sql.py", line 192
    .format(**locals()), file=f)
                             ^
SyntaxError: invalid syntax
**Expected behavior**

**Screenshots**

**ESGF Node (please complete the following information):**
 - Managed OS: RedHat7
 - Host OS: 
 - esgf-ansible Version: [e.g. v4.0.0]
 - Node type: [e.g. data-only with own IDP]

**Additional context**

**Comment by kserradell** [comment]
Same happens with decorator==4.4.2
