### ISSUE TITLE
upgrading without cert paths

### ISSUE THREAD

**Issue by gardoll** [ESGF/esgf-ansible#47]
**Describe the bug**
Trying to upgrade existing data, index and idp nodes, but esgf-ansible failed when 'Create vesgdev-idx.ipsl.upmc.fr Cert Own CA'

Full log: [upgrade_without_cert_paths.log](https://github.com/ESGF/esgf-ansible/files/2953335/upgrade_without_cert_paths.log)
```
TASK [certificate : Create vesgdev-idx.ipsl.upmc.fr Cert Own CA] ******************************************
task path: /root/tmp/esgf-ansible/roles/certificate/tasks/cert.yml:47
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1552319445.47-252336077670662/AnsiballZ_openssl_certificate.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1552319445.47-252336077670662/AnsiballZ_openssl_certificate.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1552319445.47-252336077670662/AnsiballZ_openssl_certificate.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_openssl_certificate_payload_q9dn8H/__main__.py", line 1091, in <module>
  File "/tmp/ansible_openssl_certificate_payload_q9dn8H/__main__.py", line 1070, in main
  File "/tmp/ansible_openssl_certificate_payload_q9dn8H/__main__.py", line 617, in generate
  File "/tmp/ansible_openssl_certificate_payload_q9dn8H/__main__.py", line 487, in check
  File "/tmp/ansible_openssl_certificate_payload_q9dn8H/__main__.py", line 469, in _validate_csr
IndexError: list index out of range
fatal: [vesgdev-data.ipsl.upmc.fr]: FAILED! => {
    "changed": false, 
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1552319445.47-252336077670662/AnsiballZ_openssl_certificate.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1552319445.47-252336077670662/AnsiballZ_openssl_certificate.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1552319445.47-252336077670662/AnsiballZ_openssl_certificate.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_openssl_certificate_payload_q9dn8H/__main__.py", line 1091, in <module>
  File "/tmp/ansible_openssl_certificate_payload_q9dn8H/__main__.py", line 1070, in main
  File "/tmp/ansible_openssl_certificate_payload_q9dn8H/__main__.py", line 617, in generate
  File "/tmp/ansible_openssl_certificate_payload_q9dn8H/__main__.py", line 487, in check
  File "/tmp/ansible_openssl_certificate_payload_q9dn8H/__main__.py", line 469, in _validate_csr
IndexError: list index out of range


PLAY RECAP ************************************************************************************************
vesgdev-data.ipsl.upmc.fr  : ok=105  changed=56   unreachable=0    failed=1   
vesgdev-idx.ipsl.upmc.fr   : ok=4    changed=0    unreachable=0    failed=1 
```

**To Reproduce**

```
## Conda env installation

(Installation de pip (pour python 2.6) => pip search ansible crashes.)

PARENT_DIR='/root/tmp'
cd ${PARENT_DIR}

wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh

chmod +x Miniconda2-latest-Linux-x86_64.sh
./Miniconda2-latest-Linux-x86_64.sh

source ${HOME}/.bashrc

conda create -y -n ansible python=2.7

conda activate ansible

pip install ansible==2.7

## esgf-ansible repo

PARENT_DIR='/root/tmp'
cd ${PARENT_DIR}

TAG_NAME='4.0.0-beta1'
git clone https://github.com/ESGF/esgf-ansible.git && cd esgf-ansible && git checkout $TAG_NAME

## Inventory

PARENT_DIR='/root/tmp'
cat > "${PARENT_DIR}/esgf-ansible/inventory.txt" <<EOF
[data]
vesgdev-data.ipsl.upmc.fr   ansible_connection=local

[index]
vesgdev-idx.ipsl.upmc.fr    ansible_connection=local

[idp]
vesgdev-idx.ipsl.upmc.fr   ansible_connection=local
EOF

## Host vars for vesgdev-data.ipsl.upmc.fr

PARENT_DIR='/root/tmp'
cat > "${PARENT_DIR}/esgf-ansible/host_vars/vesgdev-data.ipsl.upmc.fr.yml" <<EOF
### All paths in this file are on the machine
### on which Ansible itself will be run. That is,
### they are on the 'control' machine.

### Mirror Host
##
### The ESGF mirror to be used. Defaults to
### aims1.llnl.gov
##
### Choices:
## distrib-coffee.ipsl.jussieu.fr/pub
## dist.ceda.ac.uk
## aims1.llnl.gov
## esg-dn2.nsc.liu.se
##
mirror_host: distrib-coffee.ipsl.jussieu.fr/pub

### Prometheus Hosts and/or IPs
##
### This deployment deploys Prometheus exporters. These
### exporters report information and metrics about the node
### to a Prometheus server. The Prometheus server(s) must be
### specified so that it can be trusted to communicate with
### the exporters. Place your own Prometheus server here if
### applicable. This trust is at the webserver level.
##
### Information will not be collected until your host is added
### to the Prometheus server's target list. Remove the following
### lines if you would not like to participate in this, in which
### case only localhost will be trusted to access the exporters'
### information.
##
#prometheus_hosts:
#  - aims1.llnl.gov
#prometheus_ips:
#  - 10 # Trust your whole internal network

### Globus Services
##
### This information is used to connect the node
### to the Globus system. 
##
### Leave unspecified and the Globus Connect Server 
### setup steps will be skipped.
##
#globus_user:
#globus_pass:
#register_gridftp: true|false
#register_myproxy: true|false

### Keys and Certificates
# The priority for installing certs and keys goes like this:
# 1. Whatever is specified in the host_vars file will be installed,
#    whether or not the destination path is already present on the 
#    managed machine.
#
# 2. If the files are already present on the managed machine and 
#    nothing is specified in the host_vars file, the files that 
#    are present will be checked for validity. If the certificate is
#    found to be invalid, it will be removed and regenerated.
#
# 3. If no key and certificate files on the managed machine are
#    present and nothing is specified in the host_vars file, self-signed,
#    Ansible generated, certificates will be installed.

### Keys and Certificates for Globus Services
##
### The paths on the local machine to the respective 
### key/cert that have been signed by ESGF. If these
### have not been obtained for a node, leave unspecified.
##
### Leave unspecified and certificate signing requests for
### valid certs will be generated in the HOME directory
### of the root user.
##
#gftphostcert:
#gftphostkey:
#myproxycacert:
#myproxycakey:
#myproxy_signing_policy:

### Keys and Certificates for Web Services, httpd and tomcat
##
### The paths on the local machine to the respective 
### key/cert that have been signed by a commonly trusted 
### certificate authority.
##
### Leave unspecified and temporary, or LetsEncrypt (see below), 
### certificates will be generated.
##
#hostkey_src:
#hostcert_src:
#cachain_src:

### LetsEncrypt Certificates for Web Services
##
### LetsEncrypt certificates are browser trusted certificates
### that can be obtained in an automated fashion by proving
### you control the domain.
### In order for this to work your host must be publicly
### available at deployment time.
### This variable has no effect if the above host key/cert/chain
### variables for web services are specified.
##
### Leave unspecified to not attempt to retrieve LetsEncrypt certs.
##
#try_letsencrypt: true|false

### CentOS 6 iptables
##
### iptables is a tool that controls the Linux kernel's packet firewall.
### Many sites will likely wish to manage this on their own. If you are
### not familiar with this tool and would like this deployment to
### takes steps to configure the iptables for you on CentOS 6 then
### uncomment the below variable and set it to true. Otherwise your
### site will be responsible for ensuring the proper ports are open.
##
### Leave unspecified to manage iptables on CentOS 6 yourself.
##
#configure_centos6_iptables: true|false
EOF








## Host vars for vesgdev-idx.ipsl.upmc.fr

PARENT_DIR='/root/tmp'
cat > "${PARENT_DIR}/esgf-ansible/host_vars/vesgdev-idx.ipsl.upmc.fr.yml" <<EOF
### All paths in this file are on the machine
### on which Ansible itself will be run. That is,
### they are on the 'control' machine.

### Mirror Host
##
### The ESGF mirror to be used. Defaults to
### aims1.llnl.gov
##
### Choices:
## distrib-coffee.ipsl.jussieu.fr/pub
## dist.ceda.ac.uk
## aims1.llnl.gov
## esg-dn2.nsc.liu.se
##
mirror_host: distrib-coffee.ipsl.jussieu.fr/pub

### Prometheus Hosts and/or IPs
##
### This deployment deploys Prometheus exporters. These
### exporters report information and metrics about the node
### to a Prometheus server. The Prometheus server(s) must be
### specified so that it can be trusted to communicate with
### the exporters. Place your own Prometheus server here if
### applicable. This trust is at the webserver level.
##
### Information will not be collected until your host is added
### to the Prometheus server's target list. Remove the following
### lines if you would not like to participate in this, in which
### case only localhost will be trusted to access the exporters'
### information.
##
#prometheus_hosts:
#  - aims1.llnl.gov
#prometheus_ips:
#  - 10 # Trust your whole internal network

### Globus Services
##
### This information is used to connect the node
### to the Globus system. 
##
### Leave unspecified and the Globus Connect Server 
### setup steps will be skipped.
##
#globus_user:
#globus_pass:
#register_gridftp: true|false
#register_myproxy: true|false

### Keys and Certificates
# The priority for installing certs and keys goes like this:
# 1. Whatever is specified in the host_vars file will be installed,
#    whether or not the destination path is already present on the 
#    managed machine.
#
# 2. If the files are already present on the managed machine and 
#    nothing is specified in the host_vars file, the files that 
#    are present will be checked for validity. If the certificate is
#    found to be invalid, it will be removed and regenerated.
#
# 3. If no key and certificate files on the managed machine are
#    present and nothing is specified in the host_vars file, self-signed,
#    Ansible generated, certificates will be installed.

### Keys and Certificates for Globus Services
##
### The paths on the local machine to the respective 
### key/cert that have been signed by ESGF. If these
### have not been obtained for a node, leave unspecified.
##
### Leave unspecified and certificate signing requests for
### valid certs will be generated in the HOME directory
### of the root user.
##
#gftphostcert:
#gftphostkey:
#myproxycacert:
#myproxycakey:
#myproxy_signing_policy:

### Keys and Certificates for Web Services, httpd and tomcat
##
### The paths on the local machine to the respective 
### key/cert that have been signed by a commonly trusted 
### certificate authority.
##
### Leave unspecified and temporary, or LetsEncrypt (see below), 
### certificates will be generated.
##
#hostkey_src:
#hostcert_src:
#cachain_src:

### LetsEncrypt Certificates for Web Services
##
### LetsEncrypt certificates are browser trusted certificates
### that can be obtained in an automated fashion by proving
### you control the domain.
### In order for this to work your host must be publicly
### available at deployment time.
### This variable has no effect if the above host key/cert/chain
### variables for web services are specified.
##
### Leave unspecified to not attempt to retrieve LetsEncrypt certs.
##
#try_letsencrypt: true|false

### CentOS 6 iptables
##
### iptables is a tool that controls the Linux kernel's packet firewall.
### Many sites will likely wish to manage this on their own. If you are
### not familiar with this tool and would like this deployment to
### takes steps to configure the iptables for you on CentOS 6 then
### uncomment the below variable and set it to true. Otherwise your
### site will be responsible for ensuring the proper ports are open.
##
### Leave unspecified to manage iptables on CentOS 6 yourself.
##
#configure_centos6_iptables: true|false
EOF


## Preprocessing 

backup :
- certificate https
- certificate gridftp

* To do for vesgdev-idx

esg-node stop

rm -fr /etc/tempcerts
rm -fr /etc/certs.bak /etc/esgfcerts.bak /etc/grid-security.bak /var/lib/globus/simple_ca.bak ; cp -rp /etc/certs /etc/certs.bak ; cp -rp /etc/esgfcerts /etc/esgfcerts.bak ; cp -rp /etc/grid-security /etc/grid-security.bak ; cp -rp /var/lib/globus/simple_ca /var/lib/globus/simple_ca.bak

* To do for vesgdev-data

esg-node stop

rm -fr /etc/tempcerts
rm -fr /etc/certs.bak /etc/esgfcerts.bak /etc/grid-security.bak /var/lib/globus/simple_ca.bak ; cp -rp /etc/certs /etc/certs.bak ; cp -rp /etc/esgfcerts /etc/esgfcerts.bak ; cp -rp /etc/grid-security /etc/grid-security.bak ; cp -rp /var/lib/globus/simple_ca /var/lib/globus/simple_ca.bak

## Upgrade

export PARENT_DIR='/root/tmp'
script ${PARENT_DIR}/esgf-ansible/upgrade.log
cd ${PARENT_DIR}/esgf-ansible
source activate ansible
export ANSIBLE_NOCOLOR=true
ansible-playbook -vvv -i ${PARENT_DIR}/esgf-ansible/inventory.txt -u root install.yml
```
**Expected behavior**

upgrading done

**ESGF Node (please complete the following information):**
 - Managed OS: CentOS 6 (packages updated)
 - Host OS: CentOS 6 (from vesgdev-idx our 'all' node)
 - esgf-ansible version: 4.0.0-beta1
 - ansible version: 2.7.8

 - Node type: 

VM #1: vesgdev-idx, an 'all' esgf node that serves as index and idp node. version v2.8.1-master-release
VM #2: vesgdev-data, an data esgf node. version v2.8.1-master-release

**Additional context**

**Comment by nathanlcarlson** [comment]
Hi @gardoll, thank you for detailed account of this error. It looks somewhat familiar of something we encountered not that long ago, I will look into it right away.

**Comment by nathanlcarlson** [comment]
Hello @gardoll,
Since I already commented on this one, I will use it, although I may refer to any of the issues you reported, #47, #48, #49, or #50.

My understanding is that you would like to upgrade these two development virtual machines, vesgdev-idx and vesgdev-data using Ansible.

My first recommendation is this: 
Pick a single host to run Ansible from, whether that is one of the two VMs, or third machine such as your work station. Your inventory file should reflect this by only having `ansible_connection=local` label present on the host from which you are running Ansible. If you elect to use your workstation, then no machines would have `ansible_connection=local`.

Labeling two separate hosts with `ansible_connection=local` does not really make sense as only a single host can be "local" and may be leading to undefined behavior. 

My second recommendation: 
Do as you did in #48 regarding the specification of cert paths.

I will continue to look at the issues and post more information as I know more about what is going wrong.

**Comment by nathanlcarlson** [comment]
Hi @gardoll,

Some testing has been done, replicating some of the conditions of your deployment. Try running the deployment again after following the two recommendations above and report errors that happen from there.

Thanks for giving this a go. We appreciate you taking the time to use it and report these issues.

**Comment by gardoll** [comment]
Hi @nathanlcarlson, Thank for replying so quickly. I fixed the inventory. As you said, it was a nonsense. My apologies. I also fixed the ansible version: I thought that "pip install ansible==2.7" will install the latest version of ansible. I was, again, wrong: it installs the version 2.7.0 . So I rebuild my VM snapshots and run a new test. Unfortunately, it fails again: 
Full log: 
[fixed_inventory_without_cert_paths.log](https://github.com/ESGF/esgf-ansible/files/2956602/fixed_inventory_without_cert_paths.log)

```
TASK [certificate : Create vesgdev-data.ipsl.upmc.fr Cert Own CA] *****************************************
task path: /root/tmp/esgf-ansible/roles/certificate/tasks/cert.yml:47
fatal: [vesgdev-data.ipsl.upmc.fr]: FAILED! => {
    "changed": false, 
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDOUT:

esgf env is disable, but you can:
source /etc/esg.env
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1552389127.46-92611499006857/AnsiballZ_openssl_certificate.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1552389127.46-92611499006857/AnsiballZ_openssl_certificate.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1552389127.46-92611499006857/AnsiballZ_openssl_certificate.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_openssl_certificate_payload_8lPJCN/__main__.py", line 1091, in <module>
  File "/tmp/ansible_openssl_certificate_payload_8lPJCN/__main__.py", line 1070, in main
  File "/tmp/ansible_openssl_certificate_payload_8lPJCN/__main__.py", line 617, in generate
  File "/tmp/ansible_openssl_certificate_payload_8lPJCN/__main__.py", line 487, in check
  File "/tmp/ansible_openssl_certificate_payload_8lPJCN/__main__.py", line 469, in _validate_csr
IndexError: list index out of range


PLAY RECAP ************************************************************************************************
vesgdev-data.ipsl.upmc.fr  : ok=105  changed=56   unreachable=0    failed=1   
vesgdev-idx.ipsl.upmc.fr   : ok=105  changed=56   unreachable=0    failed=1 
```

**Comment by nathanlcarlson** [comment]
Hello @gardoll,

My understanding is that you have certificates in place on these machines and that you would like to preserve these certificates and their respective keys (they are not self-signed temporary certificates).

### Desired Mode of Operation
I believe this is the desired result right now:

>If the certificates in place are valid the user shall not need to specify anything in the host_vars file as the validity of the key/certificate pairs shall be detected, resulting in no actions required for the deployment process.

Unfortunately, this is not quite the case yet. Some checks of this nature are in place, but it appears they only work when the cert is **invalid**, and we will make sure it is fully operational in the next release.

### For Now
For now I will say to do as I recommended in my 2nd recommendation above.

> My second recommendation:
> Do as you did in #48 regarding the specification of cert paths.

These valued key/certificate pairs should be made accessible to Ansible, on the control machine, and then specified in each `host_vars` file respectively. They will then for sure be preserved and installed properly.

**Comment by gardoll** [comment]
Hi,
To be precise, The gftp and myproxy certificates are valid (from the periodicity point of view) and not self signed. The https certificates are the same as the gridftp. So they are valid to but considered as untrusted (I don't care as it is test nodes). I did a new test for the issue #48. May be I will run a test on production nodes.

**Comment by nathanlcarlson** [comment]
Hi @gardoll,

Yes, that is same definition I have for "valid" key/certificate pairs.

Sorry I missed your comment on the other issue. I have commented on it now and will look into the issue. Thanks!

**Comment by nathanlcarlson** [comment]
With #68 there are now requirements for the user to be more explicit when it comes to cert installation. So the exact desired behavior outlined above has been rejected, in favor of a more reliable, slightly less convenient solution.
