### ISSUE TITLE
upgrading with cert paths

### ISSUE THREAD

**Issue by gardoll** [ESGF/esgf-ansible#48]
**Describe the bug**
Trying to upgrade existing data, index and idp nodes, but esgf-ansible failed when 'Create vesgdev-idx.ipsl.upmc.fr Cert Own CA'

The difference between issue#47 and this issue is that the certificate paths are provided in the host_vars files.

Full log: 
[upgrade_with_cert_paths.log](https://github.com/ESGF/esgf-ansible/files/2953368/upgrade_with_cert_paths.log)

```
TASK [certificate : Create vesgdev-idx.ipsl.upmc.fr Cert Own CA] ******************************************
task path: /root/tmp/esgf-ansible/roles/certificate/tasks/cert.yml:47
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1552319967.28-83731132508851/AnsiballZ_openssl_certificate.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1552319967.28-83731132508851/AnsiballZ_openssl_certificate.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1552319967.28-83731132508851/AnsiballZ_openssl_certificate.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_openssl_certificate_payload_TOGEfY/__main__.py", line 1091, in <module>
  File "/tmp/ansible_openssl_certificate_payload_TOGEfY/__main__.py", line 1070, in main
  File "/tmp/ansible_openssl_certificate_payload_TOGEfY/__main__.py", line 617, in generate
  File "/tmp/ansible_openssl_certificate_payload_TOGEfY/__main__.py", line 487, in check
  File "/tmp/ansible_openssl_certificate_payload_TOGEfY/__main__.py", line 469, in _validate_csr
IndexError: list index out of range
fatal: [vesgdev-idx.ipsl.upmc.fr]: FAILED! => {
    "changed": false, 
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1552319967.28-83731132508851/AnsiballZ_openssl_certificate.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1552319967.28-83731132508851/AnsiballZ_openssl_certificate.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1552319967.28-83731132508851/AnsiballZ_openssl_certificate.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_openssl_certificate_payload_TOGEfY/__main__.py", line 1091, in <module>
  File "/tmp/ansible_openssl_certificate_payload_TOGEfY/__main__.py", line 1070, in main
  File "/tmp/ansible_openssl_certificate_payload_TOGEfY/__main__.py", line 617, in generate
  File "/tmp/ansible_openssl_certificate_payload_TOGEfY/__main__.py", line 487, in check
  File "/tmp/ansible_openssl_certificate_payload_TOGEfY/__main__.py", line 469, in _validate_csr
IndexError: list index out of range


PLAY RECAP ************************************************************************************************
vesgdev-data.ipsl.upmc.fr  : ok=28   changed=8    unreachable=0    failed=1   
vesgdev-idx.ipsl.upmc.fr   : ok=100  changed=48   unreachable=0    failed=1
```

**To Reproduce**

```
## Conda env installation

(Installation de pip (pour python 2.6) => pip search ansible crashes.)

PARENT_DIR='/root/tmp'
cd ${PARENT_DIR}

wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh

chmod +x Miniconda2-latest-Linux-x86_64.sh
./Miniconda2-latest-Linux-x86_64.sh

source ${HOME}/.bashrc

conda create -y -n ansible python=2.7

conda activate ansible

pip install ansible==2.7

## esgf-ansible repo

PARENT_DIR='/root/tmp'
cd ${PARENT_DIR}

TAG_NAME='4.0.0-beta1'
git clone https://github.com/ESGF/esgf-ansible.git && cd esgf-ansible && git checkout $TAG_NAME

## Inventory

PARENT_DIR='/root/tmp'
cat > "${PARENT_DIR}/esgf-ansible/inventory.txt" <<EOF
[data]
vesgdev-data.ipsl.upmc.fr   ansible_connection=local

[index]
vesgdev-idx.ipsl.upmc.fr    ansible_connection=local

[idp]
vesgdev-idx.ipsl.upmc.fr   ansible_connection=local
EOF

## Host vars for vesgdev-data.ipsl.upmc.fr

PARENT_DIR='/root/tmp'
cat > "${PARENT_DIR}/esgf-ansible/host_vars/vesgdev-data.ipsl.upmc.fr.yml" <<EOF
### All paths in this file are on the machine
### on which Ansible itself will be run. That is,
### they are on the 'control' machine.

### Mirror Host
##
### The ESGF mirror to be used. Defaults to
### aims1.llnl.gov
##
### Choices:
## distrib-coffee.ipsl.jussieu.fr/pub
## dist.ceda.ac.uk
## aims1.llnl.gov
## esg-dn2.nsc.liu.se
##
mirror_host: distrib-coffee.ipsl.jussieu.fr/pub

### Prometheus Hosts and/or IPs
##
### This deployment deploys Prometheus exporters. These
### exporters report information and metrics about the node
### to a Prometheus server. The Prometheus server(s) must be
### specified so that it can be trusted to communicate with
### the exporters. Place your own Prometheus server here if
### applicable. This trust is at the webserver level.
##
### Information will not be collected until your host is added
### to the Prometheus server's target list. Remove the following
### lines if you would not like to participate in this, in which
### case only localhost will be trusted to access the exporters'
### information.
##
#prometheus_hosts:
#  - aims1.llnl.gov
#prometheus_ips:
#  - 10 # Trust your whole internal network

### Globus Services
##
### This information is used to connect the node
### to the Globus system. 
##
### Leave unspecified and the Globus Connect Server 
### setup steps will be skipped.
##
#globus_user:
#globus_pass:
#register_gridftp: true|false
#register_myproxy: true|false

### Keys and Certificates
# The priority for installing certs and keys goes like this:
# 1. Whatever is specified in the host_vars file will be installed,
#    whether or not the destination path is already present on the 
#    managed machine.
#
# 2. If the files are already present on the managed machine and 
#    nothing is specified in the host_vars file, the files that 
#    are present will be checked for validity. If the certificate is
#    found to be invalid, it will be removed and regenerated.
#
# 3. If no key and certificate files on the managed machine are
#    present and nothing is specified in the host_vars file, self-signed,
#    Ansible generated, certificates will be installed.

### Keys and Certificates for Globus Services
##
### The paths on the local machine to the respective 
### key/cert that have been signed by ESGF. If these
### have not been obtained for a node, leave unspecified.
##
### Leave unspecified and certificate signing requests for
### valid certs will be generated in the HOME directory
### of the root user.
##
#gftphostcert:
#gftphostkey:
#myproxycacert:
#myproxycakey:
#myproxy_signing_policy:

### Keys and Certificates for Web Services, httpd and tomcat
##
### The paths on the local machine to the respective 
### key/cert that have been signed by a commonly trusted 
### certificate authority.
##
### Leave unspecified and temporary, or LetsEncrypt (see below), 
### certificates will be generated.
##
#hostkey_src:
#hostcert_src:
#cachain_src:

### LetsEncrypt Certificates for Web Services
##
### LetsEncrypt certificates are browser trusted certificates
### that can be obtained in an automated fashion by proving
### you control the domain.
### In order for this to work your host must be publicly
### available at deployment time.
### This variable has no effect if the above host key/cert/chain
### variables for web services are specified.
##
### Leave unspecified to not attempt to retrieve LetsEncrypt certs.
##
#try_letsencrypt: true|false

### CentOS 6 iptables
##
### iptables is a tool that controls the Linux kernel's packet firewall.
### Many sites will likely wish to manage this on their own. If you are
### not familiar with this tool and would like this deployment to
### takes steps to configure the iptables for you on CentOS 6 then
### uncomment the below variable and set it to true. Otherwise your
### site will be responsible for ensuring the proper ports are open.
##
### Leave unspecified to manage iptables on CentOS 6 yourself.
##
#configure_centos6_iptables: true|false

gftphostcert: /etc/grid-security.bak/hostcert.pem
gftphostkey: /etc/grid-security.bak/hostkey.pem

hostkey_src: /etc/certs.bak/hostkey.pem
hostcert_src: /etc/certs.bak/hostcert.pem
cachain_src: /etc/certs.bak/cachain.pem

EOF








## Host vars for vesgdev-idx.ipsl.upmc.fr

PARENT_DIR='/root/tmp'
cat > "${PARENT_DIR}/esgf-ansible/host_vars/vesgdev-idx.ipsl.upmc.fr.yml" <<EOF
### All paths in this file are on the machine
### on which Ansible itself will be run. That is,
### they are on the 'control' machine.

### Mirror Host
##
### The ESGF mirror to be used. Defaults to
### aims1.llnl.gov
##
### Choices:
## distrib-coffee.ipsl.jussieu.fr/pub
## dist.ceda.ac.uk
## aims1.llnl.gov
## esg-dn2.nsc.liu.se
##
mirror_host: distrib-coffee.ipsl.jussieu.fr/pub

### Prometheus Hosts and/or IPs
##
### This deployment deploys Prometheus exporters. These
### exporters report information and metrics about the node
### to a Prometheus server. The Prometheus server(s) must be
### specified so that it can be trusted to communicate with
### the exporters. Place your own Prometheus server here if
### applicable. This trust is at the webserver level.
##
### Information will not be collected until your host is added
### to the Prometheus server's target list. Remove the following
### lines if you would not like to participate in this, in which
### case only localhost will be trusted to access the exporters'
### information.
##
#prometheus_hosts:
#  - aims1.llnl.gov
#prometheus_ips:
#  - 10 # Trust your whole internal network

### Globus Services
##
### This information is used to connect the node
### to the Globus system. 
##
### Leave unspecified and the Globus Connect Server 
### setup steps will be skipped.
##
#globus_user:
#globus_pass:
#register_gridftp: true|false
#register_myproxy: true|false

### Keys and Certificates
# The priority for installing certs and keys goes like this:
# 1. Whatever is specified in the host_vars file will be installed,
#    whether or not the destination path is already present on the 
#    managed machine.
#
# 2. If the files are already present on the managed machine and 
#    nothing is specified in the host_vars file, the files that 
#    are present will be checked for validity. If the certificate is
#    found to be invalid, it will be removed and regenerated.
#
# 3. If no key and certificate files on the managed machine are
#    present and nothing is specified in the host_vars file, self-signed,
#    Ansible generated, certificates will be installed.

### Keys and Certificates for Globus Services
##
### The paths on the local machine to the respective 
### key/cert that have been signed by ESGF. If these
### have not been obtained for a node, leave unspecified.
##
### Leave unspecified and certificate signing requests for
### valid certs will be generated in the HOME directory
### of the root user.
##
#gftphostcert:
#gftphostkey:
#myproxycacert:
#myproxycakey:
#myproxy_signing_policy:

### Keys and Certificates for Web Services, httpd and tomcat
##
### The paths on the local machine to the respective 
### key/cert that have been signed by a commonly trusted 
### certificate authority.
##
### Leave unspecified and temporary, or LetsEncrypt (see below), 
### certificates will be generated.
##
#hostkey_src:
#hostcert_src:
#cachain_src:

### LetsEncrypt Certificates for Web Services
##
### LetsEncrypt certificates are browser trusted certificates
### that can be obtained in an automated fashion by proving
### you control the domain.
### In order for this to work your host must be publicly
### available at deployment time.
### This variable has no effect if the above host key/cert/chain
### variables for web services are specified.
##
### Leave unspecified to not attempt to retrieve LetsEncrypt certs.
##
#try_letsencrypt: true|false

### CentOS 6 iptables
##
### iptables is a tool that controls the Linux kernel's packet firewall.
### Many sites will likely wish to manage this on their own. If you are
### not familiar with this tool and would like this deployment to
### takes steps to configure the iptables for you on CentOS 6 then
### uncomment the below variable and set it to true. Otherwise your
### site will be responsible for ensuring the proper ports are open.
##
### Leave unspecified to manage iptables on CentOS 6 yourself.
##
#configure_centos6_iptables: true|false

myproxycacert: /var/lib/globus/simple_ca/cacert.pem
myproxycakey: /var/lib/globus/simple_ca/private/cakey.pem
myproxy_signing_policy: /var/lib/globus/simple_ca/signing-policy

hostkey_src: /etc/certs.bak/hostkey.pem
hostcert_src: /etc/certs.bak/hostcert.pem
cachain_src: /etc/certs.bak/cachain.pem

EOF


## Preprocessing 

backup :
- certificate https
- certificate gridftp

* To do for vesgdev-idx

esg-node stop

rm -fr /etc/tempcerts
rm -fr /etc/certs.bak /etc/esgfcerts.bak /etc/grid-security.bak /var/lib/globus/simple_ca.bak ; cp -rp /etc/certs /etc/certs.bak ; cp -rp /etc/esgfcerts /etc/esgfcerts.bak ; cp -rp /etc/grid-security /etc/grid-security.bak ; cp -rp /var/lib/globus/simple_ca /var/lib/globus/simple_ca.bak

* To do for vesgdev-data

esg-node stop

rm -fr /etc/tempcerts
rm -fr /etc/certs.bak /etc/esgfcerts.bak /etc/grid-security.bak /var/lib/globus/simple_ca.bak ; cp -rp /etc/certs /etc/certs.bak ; cp -rp /etc/esgfcerts /etc/esgfcerts.bak ; cp -rp /etc/grid-security /etc/grid-security.bak ; cp -rp /var/lib/globus/simple_ca /var/lib/globus/simple_ca.bak

## Upgrade

export PARENT_DIR='/root/tmp'
script ${PARENT_DIR}/esgf-ansible/upgrade.log
cd ${PARENT_DIR}/esgf-ansible
source activate ansible
export ANSIBLE_NOCOLOR=true
ansible-playbook -vvv -i ${PARENT_DIR}/esgf-ansible/inventory.txt -u root install.yml
```
**Expected behavior**

upgrading done

**ESGF Node (please complete the following information):**
 - Managed OS: CentOS 6 (packages updated)
 - Host OS: CentOS 6 (from vesgdev-idx our 'all' node)
 - esgf-ansible version: 4.0.0-beta1
 - ansible version: 2.7.8

 - Node type: 

VM #1: vesgdev-idx, an 'all' esgf node that serves as index and idp node. version v2.8.1-master-release
VM #2: vesgdev-data, an data esgf node. version v2.8.1-master-release

**Additional context**

**Comment by gardoll** [comment]
As I commented in issue#47, I fixed the inventory and the version of Ansible. I also want to report that I made a mistake about the location of the certificates of the data node (vesgdev-data). I didn't read the first lines in the example of the inventory. So I thought that the paths described in the host_vars files, were on the manage machine (in fact they must be on the control machine). In fact, I had in mind that secret keys must not leave the machine for the sake of the security.
As my control machine is the index and idp node (vesgdev-idx), I have just copied the files of the data node on the control machine (prefix /root/tmp/). So the new host_vars files end like this now: 

vesgdev-data.ipsl.upmc.fr.yml
```
gftphostcert: /root/tmp/grid-security.bak/hostcert.pem
gftphostkey: /root/tmp/grid-security.bak/hostkey.pem

hostkey_src: /root/tmp/certs.bak/hostkey.pem
hostcert_src: /root/tmp/certs.bak/hostcert.pem
cachain_src: /root/tmp/certs.bak/cachain.pem
```

vesgdev-idx.ipsl.upmc.fr.yml (nothing has changed)
```
myproxycacert: /var/lib/globus/simple_ca/cacert.pem
myproxycakey: /var/lib/globus/simple_ca/private/cakey.pem
myproxy_signing_policy: /var/lib/globus/simple_ca/signing-policy

hostkey_src: /etc/certs.bak/hostkey.pem
hostcert_src: /etc/certs.bak/hostcert.pem
cachain_src: /etc/certs.bak/cachain.pem
```

But unfortunately, It fails again: 

Full log: 
[fixed_inventory_with_cert_paths.log](https://github.com/ESGF/esgf-ansible/files/2956624/fixed_inventory_with_cert_paths.log)

```
TASK [schema_migrate : Easy Install schema migration script esgf_security_initialize] *********************
task path: /root/tmp/esgf-ansible/roles/schema_migrate/tasks/install.yml:2
fatal: [vesgdev-data.ipsl.upmc.fr]: FAILED! => {
    "changed": true, 
    "cmd": "source /usr/local/conda/bin/activate schema-migrate && easy_install /tmp/esgf_security-0.1.6-py2.7.egg", 
    "delta": "0:00:11.930831", 
    "end": "2019-03-12 12:21:30.707038", 
    "invocation": {
        "module_args": {
            "_raw_params": "source /usr/local/conda/bin/activate schema-migrate && easy_install /tmp/esgf_security-0.1.6-py2.7.egg", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": null, 
            "creates": "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/esgf_security-0.1.6-py2.7.egg", 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "rc": 1, 
    "start": "2019-03-12 12:21:18.776207"
}

STDOUT:

Processing esgf_security-0.1.6-py2.7.egg
creating /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/esgf_security-0.1.6-py2.7.egg
Extracting esgf_security-0.1.6-py2.7.egg to /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages
Adding esgf-security 0.1.6 to easy-install.pth file
Installing esgf_security_initialize script to /usr/local/conda/envs/schema-migrate/bin

Installed /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/esgf_security-0.1.6-py2.7.egg
Processing dependencies for esgf-security==0.1.6
Searching for sqlalchemy_migrate>=0.6
Reading http://rainbow.llnl.gov/dist/externals
Reading https://pypi.python.org/simple/sqlalchemy_migrate/
Downloading https://files.pythonhosted.org/packages/2a/a0/7f24bcc3a84094629bba5ca023ef982730c70b250ae2088043234ca11422/sqlalchemy-migrate-0.12.0.tar.gz#sha256=8cfada30bbcf79a83b3a2d1bcd637de7e1f43e390d54de33e4f3249fd9aacfae
Best match: sqlalchemy-migrate 0.12.0
Processing sqlalchemy-migrate-0.12.0.tar.gz
Writing /tmp/easy_install-ZjR3iR/sqlalchemy-migrate-0.12.0/setup.cfg
Running sqlalchemy-migrate-0.12.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ZjR3iR/sqlalchemy-migrate-0.12.0/egg-dist-tmp-c00EWx

Installed /tmp/easy_install-ZjR3iR/sqlalchemy-migrate-0.12.0/.eggs/pbr-5.1.3-py2.7.egg
creating /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/sqlalchemy_migrate-0.12.0-py2.7.egg
Extracting sqlalchemy_migrate-0.12.0-py2.7.egg to /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages
Adding sqlalchemy-migrate 0.12.0 to easy-install.pth file
Installing migrate script to /usr/local/conda/envs/schema-migrate/bin
Installing migrate-repository script to /usr/local/conda/envs/schema-migrate/bin

Installed /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/sqlalchemy_migrate-0.12.0-py2.7.egg
Searching for SQLAlchemy>=0.5.3
Reading https://pypi.python.org/simple/SQLAlchemy/
Downloading https://files.pythonhosted.org/packages/85/29/d7a5687d0d21ea8133f2d4ef02dfb4d191afe7ebc8bd9f962d99bdf595e1/SQLAlchemy-1.3.1.tar.gz#sha256=781fb7b9d194ed3fc596b8f0dd4623ff160e3e825dd8c15472376a438c19598b
Best match: SQLAlchemy 1.3.1
Processing SQLAlchemy-1.3.1.tar.gz
Writing /tmp/easy_install-ZnCjXe/SQLAlchemy-1.3.1/setup.cfg
Running SQLAlchemy-1.3.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ZnCjXe/SQLAlchemy-1.3.1/egg-dist-tmp-4W25KT
Moving SQLAlchemy-1.3.1-py2.7-linux-x86_64.egg to /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages
Adding SQLAlchemy 1.3.1 to easy-install.pth file

Installed /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/SQLAlchemy-1.3.1-py2.7-linux-x86_64.egg
Searching for psycopg2>=2.0
Reading https://pypi.python.org/simple/psycopg2/
Downloading https://files.pythonhosted.org/packages/63/54/c039eb0f46f9a9406b59a638415c2012ad7be9b4b97bfddb1f48c280df3a/psycopg2-2.7.7.tar.gz#sha256=f4526d078aedd5187d0508aa5f9a01eae6a48a470ed678406da94b4cd6524b7e
Best match: psycopg2 2.7.7
Processing psycopg2-2.7.7.tar.gz
Writing /tmp/easy_install-3c24W8/psycopg2-2.7.7/setup.cfg
Running psycopg2-2.7.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3c24W8/psycopg2-2.7.7/egg-dist-tmp-uC5Qh2


STDERR:

Download error on http://rainbow.llnl.gov/dist/externals: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
/usr/local/conda/envs/schema-migrate/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
warning: no files found matching 'sqla_nose.py'
no previously-included directories found matching 'doc/build/output'
zip_safe flag not set; analyzing archive contents...
Dans le fichier inclus à partir de psycopg/psycopgmodule.c:27:
./psycopg/psycopg.h:30:2: erreur: #error "Psycopg requires PostgreSQL client library (libpq) >= 9.1"

It appears you are missing some prerequisite to build the package from source.

You may install a binary package by installing 'psycopg2-binary' from PyPI.
If you want to install psycopg2 from source, please install the packages
required for the build and try again.

For further information please check the 'doc/src/install.rst' file (also at
<http://initd.org/psycopg/docs/install.html>).

error: Setup script exited with error: command 'gcc' failed with exit status 1


MSG:

non-zero return code

PLAY RECAP ************************************************************************************************
vesgdev-data.ipsl.upmc.fr  : ok=103  changed=59   unreachable=0    failed=1   
vesgdev-idx.ipsl.upmc.fr   : ok=100  changed=54   unreachable=0    failed=1
```

**Comment by gardoll** [comment]
It seems to have a problem with Psycog.

**Comment by nathanlcarlson** [comment]
Hi @gardoll,

This is good in the sense that it is no longer related to configuration options. Thanks for running this test. I will look at this error.

Thanks again!

**Comment by nathanlcarlson** [comment]
I have not yet deduced why we have not encountered this error in our testing, but it seems to be exactly as it says.

>#error "Psycopg requires PostgreSQL client library (libpq) >= 9.1"

As you are on CentOS6 you will see by doing:
```
pg_config --version
```
that CentOS 6 uses Postgres 8.4.20 (which of course is < 9.1).

This outdated database version is causing problems all over the place and I think it requires a higher level decision and call to action to address it.

### For Now
The best I can recommend, if you would like to complete the deployment, is to comment out the following lines:
6, 7 and 8 in roles/data/meta/main.yml
8 in roles/idp/meta/main.yml
3 in roles/index/meta/main.yml

Another action that can be taken, perhaps not by either of us, is to place a limit on the psycopg2 version in these schema migration setup.py's which live in different places in the ESGF Github Org's repositories. This would require rebuilding and redeploying those tools.

I will continue to try to figure out why it has not appeared in our testing. Any small difference in the state of our testing machines and your VM's could result in this and is why we are doing this testing.

**Comment by nathanlcarlson** [comment]
So it looks like our CentOS 6 deployments find a `.whl` file to use, where yours simply found a `.tar.gz` file. I am unsure why this difference has arisen.

Ours:
```
Best match: psycopg2 2.7.7
Processing psycopg2-2.7.7-cp27-cp27mu-manylinux1_x86_64.whl
Installing psycopg2-2.7.7-cp27-cp27mu-manylinux1_x86_64.whl
```
Yours:
```
Best match: psycopg2 2.7.7
Processing psycopg2-2.7.7.tar.gz
Writing /tmp/easy_install-3c24W8/psycopg2-2.7.7/setup.cfg
```

**Comment by gardoll** [comment]
You are welcome. Thank for developing the future of ESGF.

**Comment by gardoll** [comment]
Hi @nathanlcarlson !
I think it is a good idea to complete the deployment, as it may have other bugs. But it's ok if we don't succeed for now. So you are right, `pg_config --version` returns PostgreSQL 8.4.20 .
Concerning the path gftphostcert and gftphostkey, I thought it concerned the path of the certificate of Gridftp on the data node only. May be I am wrong. As you, I know just a little bit of ESGF design... If anyone can provide us a exhausted example of host_vars files, it will be brilliant. Concerning the differences between the .whl and the .tar.gz, I am not helpful, sorry.

So I commented the lines as you recommend and the upgrading has continued but failed again. My next test will be on integration nodes that have proper certificates but are esgf v2.7.1-master-release) :
Full log: 
[commented_lines_with_cert_paths.log](https://github.com/ESGF/esgf-ansible/files/2960798/commented_lines_with_cert_paths.log)


```
TASK [data : Run esginitialize] ***********************************************************************************************************************************************************************************
task path: /root/tmp/esgf-ansible/roles/data/tasks/publisher.yml:77
fatal: [vesgdev-data.ipsl.upmc.fr]: FAILED! => {
    "changed": true, 
    "cmd": "source /usr/local/conda/bin/activate esgf-pub && esginitialize -c", 
    "delta": "0:00:02.049876", 
    "end": "2019-03-13 10:09:49.726788", 
    "invocation": {
        "module_args": {
            "_raw_params": "source /usr/local/conda/bin/activate esgf-pub && esginitialize -c", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "rc": 1, 
    "start": "2019-03-13 10:09:47.676912"
}

STDERR:

/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
INFO       2019-03-13 10:09:49,659 Updating schema version directory to /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet/schema_migration
Traceback (most recent call last):
  File "/usr/local/conda/envs/esgf-pub/bin/esginitialize", line 195, in <module>
    main(sys.argv[1:])
  File "/usr/local/conda/envs/esgf-pub/bin/esginitialize", line 120, in main
    values={'repository_path':repo_path})
  File "<string>", line 1, in <lambda>
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py", line 1915, in update
    **kwargs
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/sqlalchemy/sql/dml.py", line 762, in __init__
    self._whereclause = _literal_as_text(whereclause)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 4471, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 4457, in _literal_as
    return text_fallback(element)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 4501, in _no_text_coercion
    "extra": "%s " % extra if extra else "",
sqlalchemy.exc.ArgumentError: Textual SQL expression "repository_id='ESG-CET no..." should be explicitly declared as text("repository_id='ESG-CET no...")


MSG:

non-zero return code

PLAY RECAP ********************************************************************************************************************************************************************************************************
vesgdev-data.ipsl.upmc.fr  : ok=125  changed=74   unreachable=0    failed=1   
vesgdev-idx.ipsl.upmc.fr   : ok=100  changed=54   unreachable=0    failed=1 
```

**Comment by gardoll** [comment]
I ran an upgrading tests on a pair of integration nodes. These nodes are accessible from the internet and have proper certificates. The version of ESGF installed is v2.7.1-master-release. The tests have the same configuration as issue#48 (commented lines or not, with cert paths) and it seems that they lead to the same results as my vesgdev nodes.

Cheers

**Comment by SebastienDenvil** [comment]
Hi @nathanlcarlson 

during your comment on psycopg issue you mentioned that:

> that CentOS 6 uses Postgres 8.4.20 (which of course is < 9.1). This outdated database version is causing problems all over the place and I think it requires a higher level decision and call to action to address it.

What kind of "problems" are you refering to? Do you mean we should stop supporting CentOS 6?

It looks to me that we might not be specific enough with psycopg version.

By the way psycopg should not be necessary for data node. It is needed for index node rigtht.

thanks

**Comment by nathanlcarlson** [comment]
Hi @gardoll,

### esginitialize
This error duing `esginitialize` is something we have recently started hitting and @sashakames has look into a little I believe. I will look at it more today, as well as those schema migration errors.

### MyProxy certificates
The MyProxy service is a server that issues certificates to users after they provide their credentials. It exists separate from `httpd`, as you know. Just like `httpd`, we want traffic between the server and clients to be encrypted. In order for this to be possible it is required to have a key/certificate pair to encrypt/decrypt on the server side. The key/certificate pair that does this is `/etc/grid-security/hostkey.pem` and `/etc/grid-security/hostcert.pem`. These are the `gftphostkey` and `gftphostcert`, which are unfortunately misnamed and will be repaired in the next release. This pair is also used for the GridFTP server and that is why they are named that. There is also a key/certificate pair that generates and signs the certificates that are issued to users, those are the `myproxycakey` and `myproxycacert`. So, two pairs are required to operate a MyProxy server, as I understand it.

**Comment by gardoll** [comment]
Thanks @nathanlcarlson !

**Comment by nathanlcarlson** [comment]
Hello @SebastienDenvil,

I apologize for the lack of specifics and perhaps slight exaggeration. It depends on what can be referred to as a "problem". 

The current version of Django used in our primary user interface, CoG, is using version 1.10 of Django. Where Postgres 8.4 is not officially supported, [info here](https://docs.djangoproject.com/en/2.1/releases/1.10/#dropped-support-for-postgresql-9-1). Django 1.10 also has a number CVEs which Github notifies me of occasionally.

The same lack of support for Postgres 8.4 for the later versions, > 2.7, of psycopg2. They officially support >9.1. Of course, just like with Django we can limit the version to a compatible one. 

This is the pattern though, of limiting our versions until we find the time to upgrade things. I agree that these may not be considered "problems", sorry for the exaggeration. It is likely a healthy part of any product's life. Anyway, I'd be happy to continue the discussion elsewhere, feel free to message me.

I understand it is not possible to simply say "don't use this version anymore" as many (maybe all?) ESGF Nodes are on CentOS 6. What I recommend though is that any new deployments use CentOS 7, which will now possible with this new deployment strategy.

**Comment by nathanlcarlson** [comment]
Psycopg2 is required for any place schemas or tables need to be created within the Postgres database. A Postgres database is present on data nodes to store metadata about published datasets. This info is stored in tables which are created using psycopg2.

**Comment by SebastienDenvil** [comment]
Indeed psycopg2 is a must.

As you might know yaml file has been developped to clearly describe python environment. Managing incompatible requirements has been a long running challenge for the bash installer and the docker deployment.

As you said 95% of the ESGF nodes are centOS 6 and we need to have those upgradable for a while. And yes, we need to have new deployment with centOS 7.

You can find those here.
https://github.com/ESGF/esgf-devOps

In particular for the publisher (the most complex) I think it will important to also use those for the ansible deployment.
https://github.com/ESGF/esgf-devOps/blob/master/esgf-pub_env.yml

**Comment by nathanlcarlson** [comment]
#69 Will be a part of the next release containing both the fully specified publisher environment as well as the final upgraded schema migration script. I will leave this issue open until these fixes have been verified.

**Comment by nathanlcarlson** [comment]
The issues described within this post have been resolved, head over to the release page or the master branch README to checkout the latest release.
