### ISSUE TITLE
upgrading data node only but care about idx node

### ISSUE THREAD

**Issue by gardoll** [ESGF/esgf-ansible#49]
**Describe the bug**
Trying to upgrade existing data node, but esgf-ansible failed when 'Create vesgdev-idx.ipsl.upmc.fr Cert Own CA'

This issue only differs from issue#47 by the flags `-tags data --limit vesgdev-data.ipsl.upmc.fr`.
Esgf-ansible try to create a certificate for the index node that is not supposed to be upgraded.

Full log: 
[upgrade_data_only_from_idx_without_cert_paths.log](https://github.com/ESGF/esgf-ansible/files/2953408/upgrade_data_only_from_idx_without_cert_paths.log)

```
TASK [certificate : Create vesgdev-idx.ipsl.upmc.fr Cert Own CA] ******************************************
task path: /root/tmp/esgf-ansible/roles/certificate/tasks/cert.yml:47
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1552321721.44-143578833281545/AnsiballZ_openssl_certificate.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1552321721.44-143578833281545/AnsiballZ_openssl_certificate.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1552321721.44-143578833281545/AnsiballZ_openssl_certificate.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_openssl_certificate_payload_vpLzT2/__main__.py", line 1091, in <module>
  File "/tmp/ansible_openssl_certificate_payload_vpLzT2/__main__.py", line 1070, in main
  File "/tmp/ansible_openssl_certificate_payload_vpLzT2/__main__.py", line 617, in generate
  File "/tmp/ansible_openssl_certificate_payload_vpLzT2/__main__.py", line 487, in check
  File "/tmp/ansible_openssl_certificate_payload_vpLzT2/__main__.py", line 469, in _validate_csr
IndexError: list index out of range
fatal: [vesgdev-data.ipsl.upmc.fr]: FAILED! => {
    "changed": false, 
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1552321721.44-143578833281545/AnsiballZ_openssl_certificate.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1552321721.44-143578833281545/AnsiballZ_openssl_certificate.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1552321721.44-143578833281545/AnsiballZ_openssl_certificate.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_openssl_certificate_payload_vpLzT2/__main__.py", line 1091, in <module>
  File "/tmp/ansible_openssl_certificate_payload_vpLzT2/__main__.py", line 1070, in main
  File "/tmp/ansible_openssl_certificate_payload_vpLzT2/__main__.py", line 617, in generate
  File "/tmp/ansible_openssl_certificate_payload_vpLzT2/__main__.py", line 487, in check
  File "/tmp/ansible_openssl_certificate_payload_vpLzT2/__main__.py", line 469, in _validate_csr
IndexError: list index out of range


PLAY RECAP ************************************************************************************************
vesgdev-data.ipsl.upmc.fr  : ok=105  changed=56   unreachable=0    failed=1
```

**To Reproduce**

```
## Conda env installation

(Installation de pip (pour python 2.6) => pip search ansible crashes.)

PARENT_DIR='/root/tmp'
cd ${PARENT_DIR}

wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh

chmod +x Miniconda2-latest-Linux-x86_64.sh
./Miniconda2-latest-Linux-x86_64.sh

source ${HOME}/.bashrc

conda create -y -n ansible python=2.7

conda activate ansible

pip install ansible==2.7

## esgf-ansible repo

PARENT_DIR='/root/tmp'
cd ${PARENT_DIR}

TAG_NAME='4.0.0-beta1'
git clone https://github.com/ESGF/esgf-ansible.git && cd esgf-ansible && git checkout $TAG_NAME

## Inventory

PARENT_DIR='/root/tmp'
cat > "${PARENT_DIR}/esgf-ansible/inventory.txt" <<EOF
[data]
vesgdev-data.ipsl.upmc.fr   ansible_connection=local

[index]
vesgdev-idx.ipsl.upmc.fr    ansible_connection=local

[idp]
vesgdev-idx.ipsl.upmc.fr   ansible_connection=local
EOF

## Host vars for vesgdev-data.ipsl.upmc.fr

PARENT_DIR='/root/tmp'
cat > "${PARENT_DIR}/esgf-ansible/host_vars/vesgdev-data.ipsl.upmc.fr.yml" <<EOF
### All paths in this file are on the machine
### on which Ansible itself will be run. That is,
### they are on the 'control' machine.

### Mirror Host
##
### The ESGF mirror to be used. Defaults to
### aims1.llnl.gov
##
### Choices:
## distrib-coffee.ipsl.jussieu.fr/pub
## dist.ceda.ac.uk
## aims1.llnl.gov
## esg-dn2.nsc.liu.se
##
mirror_host: distrib-coffee.ipsl.jussieu.fr/pub

### Prometheus Hosts and/or IPs
##
### This deployment deploys Prometheus exporters. These
### exporters report information and metrics about the node
### to a Prometheus server. The Prometheus server(s) must be
### specified so that it can be trusted to communicate with
### the exporters. Place your own Prometheus server here if
### applicable. This trust is at the webserver level.
##
### Information will not be collected until your host is added
### to the Prometheus server's target list. Remove the following
### lines if you would not like to participate in this, in which
### case only localhost will be trusted to access the exporters'
### information.
##
#prometheus_hosts:
#  - aims1.llnl.gov
#prometheus_ips:
#  - 10 # Trust your whole internal network

### Globus Services
##
### This information is used to connect the node
### to the Globus system. 
##
### Leave unspecified and the Globus Connect Server 
### setup steps will be skipped.
##
#globus_user:
#globus_pass:
#register_gridftp: true|false
#register_myproxy: true|false

### Keys and Certificates
# The priority for installing certs and keys goes like this:
# 1. Whatever is specified in the host_vars file will be installed,
#    whether or not the destination path is already present on the 
#    managed machine.
#
# 2. If the files are already present on the managed machine and 
#    nothing is specified in the host_vars file, the files that 
#    are present will be checked for validity. If the certificate is
#    found to be invalid, it will be removed and regenerated.
#
# 3. If no key and certificate files on the managed machine are
#    present and nothing is specified in the host_vars file, self-signed,
#    Ansible generated, certificates will be installed.

### Keys and Certificates for Globus Services
##
### The paths on the local machine to the respective 
### key/cert that have been signed by ESGF. If these
### have not been obtained for a node, leave unspecified.
##
### Leave unspecified and certificate signing requests for
### valid certs will be generated in the HOME directory
### of the root user.
##
#gftphostcert:
#gftphostkey:
#myproxycacert:
#myproxycakey:
#myproxy_signing_policy:

### Keys and Certificates for Web Services, httpd and tomcat
##
### The paths on the local machine to the respective 
### key/cert that have been signed by a commonly trusted 
### certificate authority.
##
### Leave unspecified and temporary, or LetsEncrypt (see below), 
### certificates will be generated.
##
#hostkey_src:
#hostcert_src:
#cachain_src:

### LetsEncrypt Certificates for Web Services
##
### LetsEncrypt certificates are browser trusted certificates
### that can be obtained in an automated fashion by proving
### you control the domain.
### In order for this to work your host must be publicly
### available at deployment time.
### This variable has no effect if the above host key/cert/chain
### variables for web services are specified.
##
### Leave unspecified to not attempt to retrieve LetsEncrypt certs.
##
#try_letsencrypt: true|false

### CentOS 6 iptables
##
### iptables is a tool that controls the Linux kernel's packet firewall.
### Many sites will likely wish to manage this on their own. If you are
### not familiar with this tool and would like this deployment to
### takes steps to configure the iptables for you on CentOS 6 then
### uncomment the below variable and set it to true. Otherwise your
### site will be responsible for ensuring the proper ports are open.
##
### Leave unspecified to manage iptables on CentOS 6 yourself.
##
#configure_centos6_iptables: true|false
EOF








## Host vars for vesgdev-idx.ipsl.upmc.fr

PARENT_DIR='/root/tmp'
cat > "${PARENT_DIR}/esgf-ansible/host_vars/vesgdev-idx.ipsl.upmc.fr.yml" <<EOF
### All paths in this file are on the machine
### on which Ansible itself will be run. That is,
### they are on the 'control' machine.

### Mirror Host
##
### The ESGF mirror to be used. Defaults to
### aims1.llnl.gov
##
### Choices:
## distrib-coffee.ipsl.jussieu.fr/pub
## dist.ceda.ac.uk
## aims1.llnl.gov
## esg-dn2.nsc.liu.se
##
mirror_host: distrib-coffee.ipsl.jussieu.fr/pub

### Prometheus Hosts and/or IPs
##
### This deployment deploys Prometheus exporters. These
### exporters report information and metrics about the node
### to a Prometheus server. The Prometheus server(s) must be
### specified so that it can be trusted to communicate with
### the exporters. Place your own Prometheus server here if
### applicable. This trust is at the webserver level.
##
### Information will not be collected until your host is added
### to the Prometheus server's target list. Remove the following
### lines if you would not like to participate in this, in which
### case only localhost will be trusted to access the exporters'
### information.
##
#prometheus_hosts:
#  - aims1.llnl.gov
#prometheus_ips:
#  - 10 # Trust your whole internal network

### Globus Services
##
### This information is used to connect the node
### to the Globus system. 
##
### Leave unspecified and the Globus Connect Server 
### setup steps will be skipped.
##
#globus_user:
#globus_pass:
#register_gridftp: true|false
#register_myproxy: true|false

### Keys and Certificates
# The priority for installing certs and keys goes like this:
# 1. Whatever is specified in the host_vars file will be installed,
#    whether or not the destination path is already present on the 
#    managed machine.
#
# 2. If the files are already present on the managed machine and 
#    nothing is specified in the host_vars file, the files that 
#    are present will be checked for validity. If the certificate is
#    found to be invalid, it will be removed and regenerated.
#
# 3. If no key and certificate files on the managed machine are
#    present and nothing is specified in the host_vars file, self-signed,
#    Ansible generated, certificates will be installed.

### Keys and Certificates for Globus Services
##
### The paths on the local machine to the respective 
### key/cert that have been signed by ESGF. If these
### have not been obtained for a node, leave unspecified.
##
### Leave unspecified and certificate signing requests for
### valid certs will be generated in the HOME directory
### of the root user.
##
#gftphostcert:
#gftphostkey:
#myproxycacert:
#myproxycakey:
#myproxy_signing_policy:

### Keys and Certificates for Web Services, httpd and tomcat
##
### The paths on the local machine to the respective 
### key/cert that have been signed by a commonly trusted 
### certificate authority.
##
### Leave unspecified and temporary, or LetsEncrypt (see below), 
### certificates will be generated.
##
#hostkey_src:
#hostcert_src:
#cachain_src:

### LetsEncrypt Certificates for Web Services
##
### LetsEncrypt certificates are browser trusted certificates
### that can be obtained in an automated fashion by proving
### you control the domain.
### In order for this to work your host must be publicly
### available at deployment time.
### This variable has no effect if the above host key/cert/chain
### variables for web services are specified.
##
### Leave unspecified to not attempt to retrieve LetsEncrypt certs.
##
#try_letsencrypt: true|false

### CentOS 6 iptables
##
### iptables is a tool that controls the Linux kernel's packet firewall.
### Many sites will likely wish to manage this on their own. If you are
### not familiar with this tool and would like this deployment to
### takes steps to configure the iptables for you on CentOS 6 then
### uncomment the below variable and set it to true. Otherwise your
### site will be responsible for ensuring the proper ports are open.
##
### Leave unspecified to manage iptables on CentOS 6 yourself.
##
#configure_centos6_iptables: true|false
EOF


## Preprocessing 

backup :
- certificate https
- certificate gridftp

* To do for vesgdev-idx

esg-node stop

rm -fr /etc/tempcerts
rm -fr /etc/certs.bak /etc/esgfcerts.bak /etc/grid-security.bak /var/lib/globus/simple_ca.bak ; cp -rp /etc/certs /etc/certs.bak ; cp -rp /etc/esgfcerts /etc/esgfcerts.bak ; cp -rp /etc/grid-security /etc/grid-security.bak ; cp -rp /var/lib/globus/simple_ca /var/lib/globus/simple_ca.bak

* To do for vesgdev-data

esg-node stop

rm -fr /etc/tempcerts
rm -fr /etc/certs.bak /etc/esgfcerts.bak /etc/grid-security.bak /var/lib/globus/simple_ca.bak ; cp -rp /etc/certs /etc/certs.bak ; cp -rp /etc/esgfcerts /etc/esgfcerts.bak ; cp -rp /etc/grid-security /etc/grid-security.bak ; cp -rp /var/lib/globus/simple_ca /var/lib/globus/simple_ca.bak

## Upgrade

export PARENT_DIR='/root/tmp'
script ${PARENT_DIR}/esgf-ansible/upgrade.log
cd ${PARENT_DIR}/esgf-ansible
source activate ansible
export ANSIBLE_NOCOLOR=true
ansible-playbook -vvv -i ${PARENT_DIR}/esgf-ansible/inventory.txt -u root --tags data --limit vesgdev-data.ipsl.upmc.fr install.yml
```
**Expected behavior**

upgrading done

**ESGF Node (please complete the following information):**
 - Managed OS: CentOS 6 (packages updated)
 - Host OS: CentOS 6 (from vesgdev-idx our 'all' node)
 - esgf-ansible version: 4.0.0-beta1
 - ansible version: 2.7.8

 - Node type: 

VM #1: vesgdev-idx, an 'all' esgf node that serves as index and idp node. version v2.8.1-master-release
VM #2: vesgdev-data, an data esgf node. version v2.8.1-master-release

**Additional context**

**Comment by gardoll** [comment]
As I commented in issue#47, I fixed the inventory and the version of Ansible. I also want to report that I made a mistake about the location of the certificates of the data node (vesgdev-data). I didn't read the first lines in the example of the inventory. So I thought that the paths described in the host_vars files, were on the manage machine (in fact they must be on the control machine). In fact, I had in mind that secret keys must not leave the machine for the sake of the security.
As my control machine is the index and idp node (vesgdev-idx), I have just copied the files of the data node on the control machine (prefix /root/tmp/). So the new host_vars files end like this now: 

vesgdev-data.ipsl.upmc.fr.yml
```
gftphostcert: /root/tmp/grid-security.bak/hostcert.pem
gftphostkey: /root/tmp/grid-security.bak/hostkey.pem

hostkey_src: /root/tmp/certs.bak/hostkey.pem
hostcert_src: /root/tmp/certs.bak/hostcert.pem
cachain_src: /root/tmp/certs.bak/cachain.pem
```

vesgdev-idx.ipsl.upmc.fr.yml (nothing has changed)
```
myproxycacert: /var/lib/globus/simple_ca/cacert.pem
myproxycakey: /var/lib/globus/simple_ca/private/cakey.pem
myproxy_signing_policy: /var/lib/globus/simple_ca/signing-policy

hostkey_src: /etc/certs.bak/hostkey.pem
hostcert_src: /etc/certs.bak/hostcert.pem
cachain_src: /etc/certs.bak/cachain.pem
```

But unfortunately, It fails again: 

Full log: 
[fixed_inventory_with_cert_paths.log](https://github.com/ESGF/esgf-ansible/files/2956624/fixed_inventory_with_cert_paths.log)

```
TASK [schema_migrate : Easy Install schema migration script esgf_security_initialize] *********************
task path: /root/tmp/esgf-ansible/roles/schema_migrate/tasks/install.yml:2
fatal: [vesgdev-data.ipsl.upmc.fr]: FAILED! => {
    "changed": true, 
    "cmd": "source /usr/local/conda/bin/activate schema-migrate && easy_install /tmp/esgf_security-0.1.6-py2.7.egg", 
    "delta": "0:00:11.930831", 
    "end": "2019-03-12 12:21:30.707038", 
    "invocation": {
        "module_args": {
            "_raw_params": "source /usr/local/conda/bin/activate schema-migrate && easy_install /tmp/esgf_security-0.1.6-py2.7.egg", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": null, 
            "creates": "/usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/esgf_security-0.1.6-py2.7.egg", 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "rc": 1, 
    "start": "2019-03-12 12:21:18.776207"
}

STDOUT:

Processing esgf_security-0.1.6-py2.7.egg
creating /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/esgf_security-0.1.6-py2.7.egg
Extracting esgf_security-0.1.6-py2.7.egg to /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages
Adding esgf-security 0.1.6 to easy-install.pth file
Installing esgf_security_initialize script to /usr/local/conda/envs/schema-migrate/bin

Installed /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/esgf_security-0.1.6-py2.7.egg
Processing dependencies for esgf-security==0.1.6
Searching for sqlalchemy_migrate>=0.6
Reading http://rainbow.llnl.gov/dist/externals
Reading https://pypi.python.org/simple/sqlalchemy_migrate/
Downloading https://files.pythonhosted.org/packages/2a/a0/7f24bcc3a84094629bba5ca023ef982730c70b250ae2088043234ca11422/sqlalchemy-migrate-0.12.0.tar.gz#sha256=8cfada30bbcf79a83b3a2d1bcd637de7e1f43e390d54de33e4f3249fd9aacfae
Best match: sqlalchemy-migrate 0.12.0
Processing sqlalchemy-migrate-0.12.0.tar.gz
Writing /tmp/easy_install-ZjR3iR/sqlalchemy-migrate-0.12.0/setup.cfg
Running sqlalchemy-migrate-0.12.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ZjR3iR/sqlalchemy-migrate-0.12.0/egg-dist-tmp-c00EWx

Installed /tmp/easy_install-ZjR3iR/sqlalchemy-migrate-0.12.0/.eggs/pbr-5.1.3-py2.7.egg
creating /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/sqlalchemy_migrate-0.12.0-py2.7.egg
Extracting sqlalchemy_migrate-0.12.0-py2.7.egg to /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages
Adding sqlalchemy-migrate 0.12.0 to easy-install.pth file
Installing migrate script to /usr/local/conda/envs/schema-migrate/bin
Installing migrate-repository script to /usr/local/conda/envs/schema-migrate/bin

Installed /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/sqlalchemy_migrate-0.12.0-py2.7.egg
Searching for SQLAlchemy>=0.5.3
Reading https://pypi.python.org/simple/SQLAlchemy/
Downloading https://files.pythonhosted.org/packages/85/29/d7a5687d0d21ea8133f2d4ef02dfb4d191afe7ebc8bd9f962d99bdf595e1/SQLAlchemy-1.3.1.tar.gz#sha256=781fb7b9d194ed3fc596b8f0dd4623ff160e3e825dd8c15472376a438c19598b
Best match: SQLAlchemy 1.3.1
Processing SQLAlchemy-1.3.1.tar.gz
Writing /tmp/easy_install-ZnCjXe/SQLAlchemy-1.3.1/setup.cfg
Running SQLAlchemy-1.3.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ZnCjXe/SQLAlchemy-1.3.1/egg-dist-tmp-4W25KT
Moving SQLAlchemy-1.3.1-py2.7-linux-x86_64.egg to /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages
Adding SQLAlchemy 1.3.1 to easy-install.pth file

Installed /usr/local/conda/envs/schema-migrate/lib/python2.7/site-packages/SQLAlchemy-1.3.1-py2.7-linux-x86_64.egg
Searching for psycopg2>=2.0
Reading https://pypi.python.org/simple/psycopg2/
Downloading https://files.pythonhosted.org/packages/63/54/c039eb0f46f9a9406b59a638415c2012ad7be9b4b97bfddb1f48c280df3a/psycopg2-2.7.7.tar.gz#sha256=f4526d078aedd5187d0508aa5f9a01eae6a48a470ed678406da94b4cd6524b7e
Best match: psycopg2 2.7.7
Processing psycopg2-2.7.7.tar.gz
Writing /tmp/easy_install-3c24W8/psycopg2-2.7.7/setup.cfg
Running psycopg2-2.7.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3c24W8/psycopg2-2.7.7/egg-dist-tmp-uC5Qh2


STDERR:

Download error on http://rainbow.llnl.gov/dist/externals: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
/usr/local/conda/envs/schema-migrate/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
warning: no files found matching 'sqla_nose.py'
no previously-included directories found matching 'doc/build/output'
zip_safe flag not set; analyzing archive contents...
Dans le fichier inclus à partir de psycopg/psycopgmodule.c:27:
./psycopg/psycopg.h:30:2: erreur: #error "Psycopg requires PostgreSQL client library (libpq) >= 9.1"

It appears you are missing some prerequisite to build the package from source.

You may install a binary package by installing 'psycopg2-binary' from PyPI.
If you want to install psycopg2 from source, please install the packages
required for the build and try again.

For further information please check the 'doc/src/install.rst' file (also at
<http://initd.org/psycopg/docs/install.html>).

error: Setup script exited with error: command 'gcc' failed with exit status 1


MSG:

non-zero return code

PLAY RECAP ************************************************************************************************
vesgdev-data.ipsl.upmc.fr  : ok=103  changed=59   unreachable=0    failed=1   
vesgdev-idx.ipsl.upmc.fr   : ok=100  changed=54   unreachable=0    failed=1
```

**Comment by gardoll** [comment]
It seems that it is having problem with psycog.

**Comment by gardoll** [comment]
Close because it was a side effect with an error in the inventory (read issue #47)
